version: '3.8'

services:
  api:
    build: ./back-end/
    volumes:
      - ./back-end:/app
      - /venv
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  front:
    build: ./front-end/
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  postgres_data: