"""migration

Revision ID: a5797852f397
Revises: 3d7e2a38fd9b
Create Date: 2024-07-04 01:57:16.519857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5797852f397'
down_revision: Union[str, None] = '3d7e2a38fd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('nome_professor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'nome_professor')
    # ### end Alembic commands ###
